# Generated by Django 4.1.2 on 2022-10-12 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_champ_counter_remove_task_project_delete_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rol', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='champ',
            name='rol',
        ),
        migrations.CreateModel(
            name='Champ_rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Champ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.champ')),
                ('Rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.roles')),
            ],
        ),
    ]
