# Generated by Django 4.1.2 on 2022-10-12 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_roles_remove_champ_rol_champ_rol'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Champ_rol',
            new_name='Champrol',
        ),
    ]
