# Generated by Django 4.1.2 on 2022-10-28 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_name_champ_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='Champ',
        ),
        migrations.AddField(
            model_name='counter',
            name='champ_counter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='champ', to='myapp.champ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='champ_selected',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='myapp.champ'),
            preserve_default=False,
        ),
    ]
