databases:
  - name: mysite
    databaseName: mysite
    user: mysite

services:
  - type: web
    name: mysite
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: /logica/db.sqlite3
        fromDatabase:
          name: mysite
          property: connectionString
      - key: django-insecure-e+n3l%b3z!exvk$&dy0iwlzg)%^t2^u+xr9)81=88v#esu$3o@
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4